### ISSUE TITLE
Typo in web directory module info file

### ISSUE THREAD

**Issue by dflitner** [ASUWebPlatforms/webspark-module-webspark_webdir#24]
Hey, https://github.com/ASUWebPlatforms/webspark-module-webspark_webdir/blob/main/webspark_webdir.info.yml has a typo on line 2. "Dirctory" is missing an e.

<3

**Comment by mlsamuelson** [comment]
You gotta love the fact that I mis-typed typo in the commit message. 🤦🏼 

Thanks for the heads-up, @dflitner . Appreciate it.
